### ISSUE TITLE
Styling snippets

### ISSUE THREAD

**Issue by joaolavelino** [joaolavelino/06-ingite-github-blog#13]
### Base styles:
 ```css
* {
        padding: 0;
        margin: 0;
        box-sizing: border-box;
        &:focus {
          outline: 0;
          box-shadow: 0 0 0 2px ${theme.blue[500]};
        }
        //text scale on small devices

        ${theme.mediaQuery.xsm} {
          font-size: 0.825rem;
        }
      }

 body {
        background-color: ${theme.base.mainShape};
        color: ${theme.base.text};
        font: 1rem/1.6 "Roboto", sans-serif;
        font-weight: 400;
        -webkit-font-smoothing: antialiased;
      }
button {
        outline: none;
        cursor: pointer;
        &:disabled {
          cursor: not-allowed;
          opacity: 0.5;
        }
      }
```
Quick tip for font configuration
`font: font-style font-variant font-weight font-size/line-height font-family`

### Example of animation
```css
.loading {
      animation: ${spin} 2s linear infinite;
    }
`;
```
### Animation Keyframe
keyframes is imported from styled-components
```tsx
const spin = keyframes`
  to {
          transform: rotate(360deg);
        }
`;
```
